### PR TITLE
Peter branch 1023

### PR DESCRIPTION
**Pull request by peter-mahoney**

### CODE REVIEW

**Comment by jcj-jhu** [comment]
I am good with the changes. It looked like you brought in the changes from my branch (which included Robyn's as well), even though the commit history doesn't show that

**Comment by jcj-jhu** [comment]
@peter-mahoney Do we then merge this PR and close the other ones?

**Comment by peter-mahoney** [comment]
> I am good with the changes. It looked like you brought in the changes from my branch (which included Robyn's as well), even though the commit history doesn't show that

Yeah, I didn't fully pull in the changes but the intent of the changes made it over. Sorry for messy history.

**Comment by peter-mahoney** [comment]
> @peter-mahoney Do we then merge this PR and close the other ones?

Yep that was my intent.

**Review by jcj-jhu — APPROVED** [review]

**Pull request merged**
